spring:
    datasource:
        url: jdbc:mysql://52.29.169.103:3306/synapsis_cv?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: ${USER_DB_SYNAPSIS}
        password: ${PASSWORD_DB_SYNAPSIS}