spring:
  datasource:
    url: jdbc:mysql://localhost:3306/synapsis_cv?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password:
  jpa: 
    show-sql: true