eureka:
    instance:
        leaseRenewalIntervalInSeconds: 10
        preferIpAddress: true
    client:
        registryFetchIntervalSeconds: 5
        serviceUrl:
            defaultZone: http://52.57.12.223:8761/eureka/
			
spring:
  datasource:
    url: jdbc:mysql://52.29.169.103:3306/synapsis_project?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
    username: synapsis
    password: synapsis
  jpa: 
    show-sql: true