spring:
    datasource:
        url: jdbc:mysql://bdd.ipc-synapsis.org:3306/synapsis-project?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
        username: synapsis-project 
        password: Bt2jWnYEafvWZt3E
