spring:
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        testWhileIdle: true
        validationQuery: SELECT 1
    jpa:
        database: MYSQL
        hibernate:
            ddl-auto: create
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
