spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        testWhileIdle: true
        validationQuery: SELECT 1
    jpa:
        database: MYSQL
        hibernate:
            ddl-auto: validate
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
