spring:
    datasource:
        url: jdbc:mysql://${IP_DB_SYNAPSIS_CV}:3306/synapsis_cv?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: ${USER_DB_SYNAPSIS_CV}
        password: ${PASSWORD_DB_SYNAPSIS_CV}
