spring:
    datasource:
        url: jdbc:mysql://bdd.ipc-synapsis.org:3306/synapsis-cv?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: synapsis-cv
        password: xcjLpvKmc368GyWE
