spring:
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        testWhileIdle: true
        validationQuery: SELECT 1
    jpa:
        database: MYSQL
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect


eureka:
    instance:
        leaseRenewalIntervalInSeconds: 10
    client:
        registryFetchIntervalSeconds: 5
        serviceUrl:
            defaultZone: http://52.57.12.223:8761/eureka/
    instance:
        preferIpAddress: true

logging:
  config: https://raw.githubusercontent.com/IPC-SynapsIs/synapsis-properties/master/synapsis-cv/log4j.properties
