spring:
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        testWhileIdle: true
        validationQuery: SELECT 1
    jpa:
        database: MYSQL
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
logging:
  config: https://raw.githubusercontent.com/IPC-SynapsIs/synapsis-properties/master/synapsis-cv/log4j.properties
